export { default as IpArt } from "./art"
export { default as IpTv } from "./tv"
// export { default as IpStar } from "./ip_star"
export { default as Swiper } from "./swiper"
export { default as Model } from "../../../components/model"
